version: "3.3"
services:

    # PHP service
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3307:3307"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        env_file:
            - ./.env
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 81:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    dev:
        image: "node:14.18.1-buster-slim"
        user: "node"
        working_dir: /var/www/
        volumes:
            - ./:/var/www

networks:
    app-network:
        driver: bridge
